spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2DB;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=true
    username: admin
    password: password
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest

security:
  secret: 12345678
  token-ttl: 14d

logging:
  level:
    com.javaica: debug
